config/routes.rb
Justbought::Application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}

  root 'dashboard#index'

  resources :posts do
    resources :comments, only: [ :create, :destroy ]

    member do
      get 'like'
      get 'unlike'
    end
  end

  resources :users, only: [:show] do
    member do
      get 'follow'
      get 'unfollow'
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
    @post = Post.new
    @posts = current_user.friends_posts.paginate(page: params[:page], per_page: 5)
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_comment_form.haml
.comment-form{id: "post-#{post.id}-comment"}
  = form_for [post, post.comments.build] do |f|
    .row
      .col.col-lg-8
        = f.text_field :body

app/views/dashboard/_comments.html.haml
.row
  .col-lg-12
    %ul.list-unstyled
      - post.comments.each do |comment|
        %li
          = link_to comment.user.email, user_path(comment.user)
          = comment.body
          = link_to "Delete", post_comment_path(post, comment), method: :delete

app/views/dashboard/_form.html.haml
= form_for @post, class: 'form-horizontal' do |f|
  .row
    .col.col-lg-12
      %h3= f.label :raw_comment, 'Share Something'
  .row
    .col.col-lg-9
      = f.text_field :raw_comment, placeholder: "Bought anything recently? How much do you think it's worth?"
      %span.help-block Sample : 'I just bought a new #computer it's so cool I think it is worth $500'
    .col.col-lg-3
      = submit_tag "Submit", class: 'btn btn-primary'
  = render 'shared/flash_messages'

app/views/dashboard/_post.haml
= post.media

.media-body
  .row
    .col-lg-12
      %strong= link_to post.user.email, user_path(post.user)
    .col.col-lg-12= post.parsed_comment
  .row
    .col.col-lg-12
      = link_to "Comment", '#', class: 'comment-js', data: {post: post.id}

      - if current_user
        |
        - if current_user.likes_post?(post)
          = link_to "Unlike", unlike_post_path(post)
        - else
          = link_to "like", like_post_path(post)

      - if post.user_id.eql?(current_user.id)
        |
        = link_to "Delete", post_path(post), method: :delete
  = render 'dashboard/comments', post: post
  = render 'dashboard/comment_form', post: post

app/views/dashboard/_posts.haml
%ul.feed.media-list
  - posts.each do |post|
    %li.media
      = render '/dashboard/post', post: post
= will_paginate(posts)

app/views/dashboard/_stream_row.haml
= post.media

.media-body
  .row
    .col-lg-12
      %strong= link_to post.user.email, user_path(post.user)
    .col.col-lg-12= post.parsed_comment
  .row
    .col.col-lg-3
      = link_to "comment", '#'
      |
      = link_to "like", '#'
      - if post.user_id.eql?(current_user.id)
        |
        = link_to "delete", post_path(post), method: :delete

app/views/dashboard/index.haml
.row
  .col.col-lg-8
    = render 'form'

    = render 'dashboard/posts', posts: @posts

  = render 'layouts/sidebar'